# -*- coding: utf-8 -*-
import statistics
import scipy.stats as sts
from scipy.stats import norm
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.mlab as mlab
print("Homework 1: Hailey Kryszewski 124001456")
print("Question 1:\n")
print("Mean Median and Mode for FE_H")
astroValuesFE=[-.60,-.63,-.57,-.53,-.6,-.6,-.54,-.63,-.49,-.63,-.68,-.51,-.47,-.54,-.58,-.60,-.69,-.42,-.60,-.55,-.38,-.81,-.48,-.56,-.56,-.53,-.55,-.47,-.54,-.58,-.60,-.69,-.42,-.60,-.55,-.38,-.81,-.48,-.56,-.49,-.32,-.52,-.53,-.7,-.43,-.4,-.3,-.3]
meanVal= statistics.mean(astroValuesFE)
print("The mean value of FE_H is: ", meanVal)
medianVal= statistics.median(astroValuesFE)
print("The median value of FE_H is: ", medianVal)
modeVal= statistics.mode(astroValuesFE)
print("The mode value of FE_H is: ", modeVal)
stdVal= statistics.stdev(astroValuesFE)
print("The standard deviation of FE_H is: ", stdVal)
print("Mean Median and Mode for oRV")
astroValuesoRV=[-5.2,-4.4,-5.5,-5.2,-5.9,-7.4,-7.1,-4.8,-5.8,-6.1,-5.4,-3.2,-4.7,-6.6,-4.6,-3.9,-5.6,-5.2,-4.7,-3.9,-5.3,-7.0,-5.4,-2.3,-5.3,-6.7,-5.6,-5.3,-6.8,-5.5,-5.0,-6.2,-8.0,-4.7,-4.6,-5.2,-6.0,-5.8]
meanVal= statistics.mean(astroValuesoRV)
print("The mean value of oRV is: ", meanVal)
medianVal= statistics.median(astroValuesoRV)
print("The median value of oRV is: ", medianVal)
modeVal= statistics.mode(astroValuesoRV)
print("The mode value of oRV is: ", modeVal)
stdVal= statistics.stdev(astroValuesoRV)
print("The standard deviation of oRV is: ", stdVal)
print("Mean Median and Mode for PLX")
astroValuespLX=[0.089,0.089,0.088,0.095,0.090,0.086,0.076,0.092]
meanVal= statistics.mean(astroValuespLX)
print("The mean value of PLX is: ", meanVal)
medianVal= statistics.median(astroValuespLX)
print("The median value of PLX is: ", medianVal)
modeVal= statistics.mode(astroValuespLX)
print("The mode value of PLX is: ", modeVal)
stdVal= statistics.stdev(astroValuespLX)
print("The standard deviation of PLX is: ", stdVal)
print("Mean Median and Mode for PM")
astroValuesPM=[-1093,-1093,-1086,-1102,-1098,-1110]
meanVal= statistics.mean(astroValuesPM)
print("The mean value of PLX is: ", meanVal)
medianVal= statistics.median(astroValuesPM)
print("The median value of PLX is: ", medianVal)
modeVal= statistics.mode(astroValuesPM)
print("The mode value of PLX is: ", modeVal)
stdVal= statistics.stdev(astroValuesPM)
print("The standard deviation of PLX is: ", stdVal)
print("Mean Median and Mode for Velocities")
astroValuesV=[-4.9,-5.2,-5.19,-5.24,-4.6,-5.2,-5.5,-4.4,-5.8,-6,-5.2,-4.6,-4.7,-8,-6.2,-5.2,-5,-6.8,-5.3,-5.6,-5.5,-5.3,-2.3,-6.7,-5.4,-7,-5.3,-3.9,-4.7,-5.2,-5.6,-3.9,-4.6,-6.6,-4.7,-3.2,-5.4,-6.1,-5.8,4.8,-7.1,-5.9,-7.4]
meanVal= statistics.mean(astroValuesV)
print("The mean value of PLX is: ", meanVal)
medianVal= statistics.median(astroValuesV)
print("The median value of PLX is: ", medianVal)
modeVal= statistics.mode(astroValuesV)
print("The mode value of PLX is: ", modeVal)
stdVal= statistics.stdev(astroValuesV)
print("The standard deviation of PLX is: ", stdVal)
print("Question 2:\n")
print("The fe_h value represents the metallicity. In other words, this value represents what part of the mass is not Hydrogen or Helium.\n")
print("The oRV value represents the radial velocity of the star in orbit. It is the value of the rate of change in distance of a star or celestial body and a point.\n")
print("The PLX value represents the parallax to a given star.\n")
print("The PM value represents the proper motion of the star is the movement of a closer star across the sky in relation to further away stars.\n")
print("The velocities represent how fast the star is moving.\n")
print("Question 3:\n")
sampVar= statistics.variance(astroValuesPM)
print("The sample variance of PM is ", sampVar)
popVar= statistics.pvariance(astroValuesPM)
print("The population variance of PM is ", popVar, "\n")
print("Python defaults to the sample variance.\n")
print("Question 4 and 5:\n")
feMean=np.mean(astroValuesFE)
feStd=np.std(astroValuesFE)
astroValuesFE.sort()
pmMean=np.mean(astroValuesPM)
pmStd=np.std(astroValuesPM)
astroValuesPM.sort()
vMean=np.mean(astroValuesV)
vStd=np.std(astroValuesV)
astroValuesV.sort()
orvMean=np.mean(astroValuesoRV)
orvStd=np.std(astroValuesoRV)
astroValuesoRV.sort()
plxMean=statistics.mean(astroValuespLX)
plxStd=statistics.stdev(astroValuespLX)
astroValuespLX.sort()
plt.subplot(3, 2, 1)
(feMean,feStd)=norm.fit(astroValuesFE)
n,bins, patches=plt.hist(astroValuesFE,50,normed=True,facecolor='green',alpha=.75)
y=mlab.normpdf(bins,feMean,feStd)
l=plt.plot(bins,y,'r--',linewidth=2)
plt.xlabel('fe_h Values')
plt.ylabel('Probability')
plt.grid(True)
plt.subplots_adjust(hspace=.35)
plt.subplot(3, 2, 3)
(pmMean,pmStd)=norm.fit(astroValuesPM)
n,bins, patches=plt.hist(astroValuesPM,6,normed=True,facecolor='blue',alpha=.75)
y=mlab.normpdf(bins,pmMean,pmStd)
l=plt.plot(bins,y,'r--',linewidth=2)
plt.xlabel('PM Values (mas*yr^-1)')
plt.ylabel('Probability')
plt.grid(True)
plt.subplots_adjust(hspace=.35)
plt.subplot(3, 2, 4)
(vMean,vStd)=norm.fit(astroValuesV)
n,bins, patches=plt.hist(astroValuesV,40,normed=True,facecolor='pink',alpha=.75)
y=mlab.normpdf(bins,vMean,vStd)
l=plt.plot(bins,y,'r--',linewidth=2)
plt.xlabel('Velocity Values')
plt.ylabel('Probability')
plt.grid(True)
plt.subplots_adjust(hspace=.35)
plt.subplot(3, 2, 5)
(orvMean,orvStd)=norm.fit(astroValuesoRV)
n,bins, patches=plt.hist(astroValuesoRV,50,normed=True,facecolor='green',alpha=.75)
y=mlab.normpdf(bins,orvMean,orvStd)
l=plt.plot(bins,y,'r--',linewidth=2)
plt.xlabel('ORV Values (km/s)')
plt.ylabel('Probability')
plt.grid(True)
plt.subplots_adjust(hspace=.5)
plt.subplot(3, 2, 6)
(plxMean,plxStd)=norm.fit(astroValuespLX)
n,bins, patches=plt.hist(astroValuespLX,10,normed=True,facecolor='orange',alpha=.75)
y=mlab.normpdf(bins,plxMean,plxStd)
l=plt.plot(bins,y,'r--',linewidth=2)
plt.xlabel('PLX Values (arcsec)')
plt.ylabel('Probability')
plt.grid(True)
plt.tight_layout()
plt.subplots_adjust(hspace=.5)
plt.show()
print('The data appears to follow a normal distribution.\n')
print('Question 6')
print('Assuming the same astronomer using the same telescope, the statistical error will result from the difference of the amount of measurements taken. For example, the fe_h list of values has 48 elements where as the PLX list only has 8. This is because fe_h has a broader base of values to give a more accurate distribution. In order of statistical error from most statistically error prone to least statistically error prone is PM, PLX, oRV, Velocities, fe_h. The systematic error of the system is much easier to predict since it is the same astronomer and the same instrument. The systematic error should be uniform across all measurements.')